# Q11.
```{admonition}
:class: note
In this problem we will investigate the t-statistic for the null hypothesis $H_{0}: \beta = 0$ in simple linear regression without an intercept. To begin, we generate a predictor `x` and a response `y` as follows.

In [1]:
import numpy as np
import statsmodels.api as sm
from ISLP.models import summarize

In [2]:
rng = np.random.default_rng(1728)
x = rng.normal(size=100)
y = 2*x+rng.normal(size=100)

## (a)
```{admonition}
:class: note
Perform a simple linear regression of `y` onto `x`, *without* an intercept. Report the coefficient esimate, the standard error of this estimate, and the $t$-statistic and $p$-value associated with the null hypothesis $H_{0}:\beta = 0$.

In [3]:
model1 = sm.OLS(y,x).fit()
summarize(model1)

      coef  std err       t  P>|t|
x1  1.9507    0.086  22.668    0.0

## (b)
```{admonition}
:class: note
Now perform a simple linear regression of `x` onto `y` without an intercept, and report the coefficient estimate, its standard error, and the corresponding $t$-statistic and $p$-values associated with the null hypothesis $H_{0}:\beta = 0$.

In [4]:
model2 = sm.OLS(x,y).fit()
summarize(model2)

      coef  std err       t  P>|t|
x1  0.4298    0.019  22.668    0.0

## (c)
```{admonition}
:class: note
What is the relationship between the results obtained in (a) and (b)?

The coefficient in the first case is $\operatorname{Cov}(X,Y)/\operatorname{Var}(X)$ and in the second case is $\operatorname{Cov}(X,Y)/\operatorname{Var}(Y)$. Their product is then
$$
\frac{\operatorname{Cov}(X,Y)^{2}}{\operatorname{Var}(X)\operatorname{Var}(Y)} = r^{2},
$$
the squared correlation coefficient.

The $t$-statistic is the same in both models.

## (d)
```{admonition}
:class: note
For the regression of $Y$ onto $X$ without an intercept, the $t$-statistic for $H_{0}: \beta = 0$ takes the form $\hat{\beta}/\operatorname{SE}(\hat{\beta})$, where $$\hat{\beta} = \frac{\sum_{i=1}^{n}x_{i}y_{i}}{\sum_{i=1}^{n}x_{i}^{2}}$$ and $$\operatorname{SE}(\hat{\beta}) = \sqrt{\frac{\sum_{i=1}^{n}(y_{i}-x_{i}\hat{\beta})^{2}}{(n-1)\sum_{i=1}^{n}x_{i}^{2}}}.$$ Show algebraically and confirm numerically that the $t$-statistic can be written as
$$
\frac{\sqrt{n-1}\sum_{i=1}^{n}x_{i}y_{i}}{\sqrt{(\sum_{i=1}^{n}x_{i}^{2})(\sum_{i=1}^{n}y_{i}^{2})-(\sum_{i=1}^{n}x_{i}y_{i})^{2}}}.
$$

For ease of notation, we write
$$
\begin{align*}
V_{x} &= \sum_{i=1}^{n}x_{i}^{2}\\
V_{y} &= \sum_{i=1}^{n}y_{i}^{2}\\
V_{xy} &= \sum_{i=1}^{n}x_{i}y_{i}.
\end{align*}
$$

Then note $\hat{\beta} = V_{xy}/V_{x}$ and 
$$
\operatorname{SE}(\hat{\beta})^{2}
= \frac{\sum_{i=1}^{n}y_{i}^{2}-2y_{i}x_{i}\hat{\beta}+x_{i}^{2}\hat{\beta}^{2}}{(n-1)\sum_{i=1}^{n}x_{i}^{2}}
= \frac{V_{y}-2\hat{\beta}V_{xy}+\hat{\beta}^{2}V_{x}}{(n-1)V_{x}}
= \frac{V_{y}-(2V_{xy}V_{xy}/V_{x})+(V_{xy}^{2}V_{x}/V_{x}^{2})}{(n-1)V_{x}}
= \frac{V_{x}V_{y}-V_{xy}^{2}}{(n-1)V_{x}^{2}}
$$

Then we have the $t$-statistic has the form
$$
\frac{\hat{\beta}}{\operatorname{SE}(\hat{\beta})} = \frac{V_{xy}/V_{x}}{\sqrt{V_{x}V_{y}-V_{xy}^{2}}/(\sqrt{n-1}V_{x})} = \frac{\sqrt{n-1}V_{xy}}{\sqrt{V_{x}V_{y}-V_{xy}^{2}}}
$$
which is in the form to be shown.$\hspace{25cm}\square$

In [18]:
vxy = (x*y).sum()
vx = (x**2).sum()
vy = (y**2).sum()
n = 100
t_stat_mod = model1.tvalues[0]
t_stat_alg = np.sqrt(n-1)*vxy/np.sqrt(vx*vy-vxy**2)
print(f'The t-statistic from the model is {t_stat_mod:.5f} and the t-statistic computed using the algebraic form is {t_stat_alg:.5f}.')

The t-statistic from the model is 22.66789 and the t-statistic computed using the algebraic form is 22.66789.

## (e)
```{admonition}
:class: note
Using the result form (d), argue that the $t$-statistic for the regression of `y` onto `x` is the same as the $t$-statistic for the regression of `x` onto `y`.

The $t$-statistic is symmetric in `x` and `y`, and therefore regressing `y` onto `x` gives the same $t$-statistic as regressing `x` onto `y`.

## (f)
```{admonition}
:class: note
Show numerically that when regression is performed with an intercept, the $t$-statistic for $H_{0}: \beta_{1} = 0$ is the same for the regression of `y` onto `x` as it is for the regression of `x` onto `y`.

In [20]:
model3 = sm.OLS(y,sm.add_constant(x)).fit()
model4 = sm.OLS(x,sm.add_constant(y)).fit()

In [24]:
model3.tvalues[1] == model4.tvalues[1]

np.True_